Repository strivesolutions/flutter_empire, pull requests merged in 2022-08, with the labels that each got.

#53 Update README.MD for strive switch over
  README.md
Labels: documentation

#54 Update README
  README.md
  examples/counter/lib/counter_page.dart
  examples/counter/lib/main.dart
  lib/empire_bool_property.dart
Labels: documentation, enhancement

#55 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
  README.md
Labels: documentation

#59 0.8.1 Release
  pubspec.yaml
Labels: Version Change

#64 0.8.2 Release
  CHANGELOG.md
  README.md
  pubspec.yaml
Labels: Version Change

#65 0.8.3 Release
  CHANGELOG.md
  README.md
  pubspec.yaml
Labels: documentation, Version Change

#67 Add Increment and Decrement to EmpireIntProperty
  lib/empire_int_property.dart
  test/empire_property_tests/int_property_test.dart
Labels: enhancement

#69 Publish to pub when release is published
  .github/workflows/release_published.yml
Labels: CI / CD Workflows
