Repository strivesolutions/flutter_empire, pull requests merged in 2022-06, with the labels that each got.

#2 Documentation Fixes / Clean up
  lib/empire_state.dart
  lib/empire_view_model.dart
  lib/empire_widget.dart
Labels: documentation

#5 Add pubspec.lock to gitignore
  .gitignore
  pubspec.lock
Labels: bug

#12 Add Reset Feature to EmpireProperty
  lib/empire_view_model.dart
  test/empire_property_test.dart
Labels: enhancement

#14 EmpireState Documentation
  lib/empire_state.dart
Labels: documentation

#15 EmpireProperty Equality Check Improvements
  lib/empire_view_model.dart
  test/empire_property_test.dart
Labels: enhancement

#18 Add Type Specific Empire Properties
  examples/counter/lib/application_view_model.dart
  examples/counter/lib/counter_page.dart
  examples/counter/lib/counter_view_model.dart
  examples/counter/lib/main.dart
  lib/empire.dart
  lib/empire_bool_property.dart
  lib/empire_double_property.dart
  lib/empire_exceptions.dart
  lib/empire_int_property.dart
  lib/empire_list_property.dart
  lib/empire_map_property.dart
  lib/empire_property.dart
  lib/empire_string_property.dart
  lib/empire_view_model.dart
  test/empire_property_tests/bool_property_test.dart
  test/empire_property_tests/double_property_test.dart
  test/empire_property_tests/empire_property_test.dart
  test/empire_property_tests/int_property_test.dart
  test/empire_property_tests/list_property_test.dart
  test/empire_property_tests/map_property_test.dart
  test/empire_property_tests/string_property_test.dart
  test/empire_view_model_test.dart
  test/empire_widget_test.dart
Labels: enhancement

#22 Release Automation
  .github/workflows/pre-release.yml
  pubspec.yaml
  versionChangeCheck.sh
Labels: CI / CD Workflows

#24 Typo in release PR workflow
  .github/workflows/release_pr.yml
Labels: documentation

#25 Support Multiple Empires
  examples/counter/lib/counter_page.dart
  lib/empire_widget.dart
  test/empire_widget_test.dart
Labels: enhancement

#28 Short-hand Busy Status Update Functions
  lib/empire_view_model.dart
Labels: enhancement

#27 Null Check Properties on EmpireProperty
  lib/empire_bool_property.dart
  lib/empire_double_property.dart
  lib/empire_int_property.dart
  lib/empire_property.dart
  lib/empire_string_property.dart
  test/empire_property_tests/empire_property_test.dart
Labels: enhancement

#29 Fix Map Function on EmpireListProperty
  lib/empire_list_property.dart
  test/empire_property_tests/list_property_test.dart
Labels: bug

#35 Fix internally tracked original values for list and map
  lib/empire_list_property.dart
  lib/empire_map_property.dart
  lib/empire_property.dart
  lib/empire_view_model.dart
  test/empire_property_tests/list_property_test.dart
  test/empire_property_tests/map_property_test.dart
Labels: bug

#34 Fixed incorrect variable name in documentation
  docs/empire_property/EmpireIntProperty-class.html
  lib/empire_int_property.dart
Labels: documentation

#38 Extensions on Lists of EmpireStateChanged events
  lib/empire_view_model.dart
  test/empire_state_changed_test.dart
Labels: enhancement

#37 New helper set methods for bool properties
  lib/empire_bool_property.dart
  test/empire_property_tests/bool_property_test.dart
Labels: enhancement

#40 Fixing stream issues and improving docs
  examples/counter/.gitignore
  examples/counter/pubspec.lock
  lib/empire_state.dart
  lib/empire_view_model.dart
Labels: bug

#42 Debug Print State Changes
  images/Empire Social Media Image.png
  lib/empire_state.dart
  lib/empire_widget.dart
Labels: enhancement

#44 Fix BusyTaskKey Bug
  lib/empire_view_model.dart
  lib/empire_widget.dart
Labels: bug

#47 Change Notification Improvements
  lib/empire_property.dart
  lib/empire_view_model.dart
Labels: enhancement

#49 EmpireDateTimeProperty
  lib/empire_date_time_property.dart
  lib/empire_property.dart
  lib/empire_view_model.dart
  test/empire_property_tests/date_time_property_test.dart
Labels: enhancement

#51 Set multiple doesn't work when Empire Property keys have null values
  .vscode/settings.json
  lib/empire_view_model.dart
  test/empire_widget_test.dart
Labels: bug
